[project]
name = "musializer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyqt5>=5.15.11",
    "tkinterdnd2>=0.4.3",
]
